import type { DrawPlayer } from './team-builder';

type SeedPlayer = Omit<DrawPlayer, 'id'>;

export const SEED_PLAYERS: SeedPlayer[] = [
  // Goleiros (10)
  { name: 'Oliver Kahn',          nickname: 'Kaiser Kahn',   stars: 5, position: 'goalkeeper', active: true },
  { name: 'Gianluigi Buffon',     nickname: 'Buffon',        stars: 5, position: 'goalkeeper', active: true },
  { name: 'Peter Schmeichel',     nickname: 'Schmeichel',    stars: 5, position: 'goalkeeper', active: true },
  { name: 'Iker Casillas',        nickname: 'San Iker',      stars: 5, position: 'goalkeeper', active: true },
  { name: 'Alisson Becker',       nickname: 'Alisson',       stars: 5, position: 'goalkeeper', active: true },
  { name: 'Manuel Neuer',         nickname: 'Neuer',         stars: 5, position: 'goalkeeper', active: true },
  { name: 'Dida',                 nickname: 'Dida',          stars: 4, position: 'goalkeeper', active: true },
  { name: 'Fabien Barthez',       nickname: 'Barthez',       stars: 4, position: 'goalkeeper', active: true },
  { name: 'Edwin van der Sar',    nickname: 'Van der Sar',   stars: 4, position: 'goalkeeper', active: true },
  { name: 'Víctor Valdés',        nickname: 'Valdés',        stars: 3, position: 'goalkeeper', active: true },

  // Laterais (14)
  { name: 'Roberto Carlos',       nickname: 'Roberto Carlos', stars: 5, position: 'fullback', active: true },
  { name: 'Cafu',                 nickname: 'Cafu',           stars: 5, position: 'fullback', active: true },
  { name: 'Philipp Lahm',         nickname: 'Lahm',           stars: 5, position: 'fullback', active: true },
  { name: 'Dani Alves',           nickname: 'Dani Alves',     stars: 5, position: 'fullback', active: true },
  { name: 'Marcelo Vieira',       nickname: 'Marcelo',        stars: 5, position: 'fullback', active: true },
  { name: 'Lilian Thuram',        nickname: 'Thuram',         stars: 4, position: 'fullback', active: true },
  { name: 'Ashley Cole',          nickname: 'Ashley Cole',    stars: 4, position: 'fullback', active: true },
  { name: 'Maicon Douglas',       nickname: 'Maicon',         stars: 4, position: 'fullback', active: true },
  { name: 'Gianluca Zambrotta',   nickname: 'Zambrotta',      stars: 4, position: 'fullback', active: true },
  { name: 'Jordi Alba',           nickname: 'Jordi Alba',     stars: 4, position: 'fullback', active: true },
  { name: 'David Alaba',          nickname: 'Alaba',          stars: 4, position: 'fullback', active: true },
  { name: 'Bixente Lizarazu',     nickname: 'Lizarazu',       stars: 4, position: 'fullback', active: true },
  { name: 'Gary Neville',         nickname: 'G. Neville',     stars: 3, position: 'fullback', active: true },
  { name: 'Wael Gomaa',           nickname: 'Cafú Egípcio',   stars: 2, position: 'fullback', active: true },

  // Zagueiros (18)
  { name: 'Paolo Maldini',        nickname: 'Maldini',       stars: 5, position: 'defender', active: true },
  { name: 'Fabio Cannavaro',      nickname: 'Cannavaro',     stars: 5, position: 'defender', active: true },
  { name: 'Alessandro Nesta',     nickname: 'Nesta',         stars: 5, position: 'defender', active: true },
  { name: 'Carles Puyol',         nickname: 'Puyol',         stars: 5, position: 'defender', active: true },
  { name: 'Thiago Silva',         nickname: 'Thiago Silva',  stars: 5, position: 'defender', active: true },
  { name: 'Sergio Ramos',         nickname: 'Ramos',         stars: 5, position: 'defender', active: true },
  { name: 'Virgil van Dijk',      nickname: 'VVD',           stars: 5, position: 'defender', active: true },
  { name: 'Rio Ferdinand',        nickname: 'Rio',           stars: 4, position: 'defender', active: true },
  { name: 'Marcel Desailly',      nickname: 'Desailly',      stars: 4, position: 'defender', active: true },
  { name: 'Fernando Hierro',      nickname: 'Hierro',        stars: 4, position: 'defender', active: true },
  { name: 'Lúcio',                nickname: 'Lúcio',         stars: 4, position: 'defender', active: true },
  { name: 'John Terry',           nickname: 'JT',            stars: 4, position: 'defender', active: true },
  { name: 'Raphaël Varane',       nickname: 'Varane',        stars: 4, position: 'defender', active: true },
  { name: 'Jaap Stam',            nickname: 'Jaap Stam',     stars: 4, position: 'defender', active: true },
  { name: 'Pepe',                 nickname: 'Pepe',          stars: 4, position: 'defender', active: true },
  { name: 'Aldair',               nickname: 'Aldair',        stars: 4, position: 'defender', active: true },
  { name: 'Roberto Ayala',        nickname: 'Ayala',         stars: 3, position: 'defender', active: true },
  { name: 'Alessandro Costacurta', nickname: 'Costacurta',  stars: 3, position: 'defender', active: true },

  // Meias (30)
  { name: 'Zinedine Zidane',      nickname: 'Zizou',         stars: 5, position: 'midfielder', active: true },
  { name: 'Ronaldinho Gaúcho',    nickname: 'Ronaldinho',    stars: 5, position: 'midfielder', active: true },
  { name: 'Rivaldo',              nickname: 'Rivaldo',       stars: 5, position: 'midfielder', active: true },
  { name: 'David Beckham',        nickname: 'Beckham',       stars: 5, position: 'midfielder', active: true },
  { name: 'Kaká',                 nickname: 'Kaká',          stars: 5, position: 'midfielder', active: true },
  { name: 'Pavel Nedvěd',         nickname: 'Nedvěd',        stars: 5, position: 'midfielder', active: true },
  { name: 'Luis Figo',            nickname: 'Figo',          stars: 5, position: 'midfielder', active: true },
  { name: 'Andrea Pirlo',         nickname: 'Pirlo',         stars: 5, position: 'midfielder', active: true },
  { name: 'Xavi Hernández',       nickname: 'Xavi',          stars: 5, position: 'midfielder', active: true },
  { name: 'Andrés Iniesta',       nickname: 'Iniesta',       stars: 5, position: 'midfielder', active: true },
  { name: 'Luka Modrić',          nickname: 'Modrić',        stars: 5, position: 'midfielder', active: true },
  { name: 'Juan Román Riquelme',  nickname: 'Riquelme',      stars: 5, position: 'midfielder', active: true },
  { name: 'Michael Laudrup',      nickname: 'Laudrup',       stars: 5, position: 'midfielder', active: true },
  { name: 'Gheorghe Hagi',        nickname: 'Hagi',          stars: 5, position: 'midfielder', active: true },
  { name: 'Carlos Valderrama',    nickname: 'Valderrama',    stars: 5, position: 'midfielder', active: true },
  { name: 'Roberto Baggio',       nickname: 'Roberto Baggio', stars: 5, position: 'midfielder', active: true },
  { name: 'Toni Kroos',           nickname: 'Kroos',         stars: 5, position: 'midfielder', active: true },
  { name: 'N\'Golo Kanté',        nickname: 'Kanté',         stars: 5, position: 'midfielder', active: true },
  { name: 'Frank Lampard',        nickname: 'Lampard',       stars: 4, position: 'midfielder', active: true },
  { name: 'Steven Gerrard',       nickname: 'Gerrard',       stars: 4, position: 'midfielder', active: true },
  { name: 'Patrick Vieira',       nickname: 'Vieira',        stars: 4, position: 'midfielder', active: true },
  { name: 'Roy Keane',            nickname: 'Keane',         stars: 4, position: 'midfielder', active: true },
  { name: 'Clarence Seedorf',     nickname: 'Seedorf',       stars: 4, position: 'midfielder', active: true },
  { name: 'Edgar Davids',         nickname: 'Pitbull',       stars: 4, position: 'midfielder', active: true },
  { name: 'Paul Scholes',         nickname: 'Scholes',       stars: 4, position: 'midfielder', active: true },
  { name: 'Michael Ballack',      nickname: 'Ballack',       stars: 4, position: 'midfielder', active: true },
  { name: 'Gennaro Gattuso',      nickname: 'Gattuso',       stars: 4, position: 'midfielder', active: true },
  { name: 'Claude Makélélé',      nickname: 'Makélélé',      stars: 4, position: 'midfielder', active: true },
  { name: 'Sócrates',             nickname: 'Sócrates',      stars: 5, position: 'midfielder', active: true },
  { name: 'Neymar Jr',            nickname: 'Neymar',        stars: 5, position: 'midfielder', active: true },

  // Atacantes (28)
  { name: 'Ronaldo Fenômeno',     nickname: 'Fenômeno',      stars: 5, position: 'forward', active: true },
  { name: 'Thierry Henry',        nickname: 'Henry',         stars: 5, position: 'forward', active: true },
  { name: 'Adriano Imperador',    nickname: 'Imperador',     stars: 5, position: 'forward', active: true },
  { name: 'Raúl González',        nickname: 'Raúl',          stars: 5, position: 'forward', active: true },
  { name: 'Alessandro Del Piero', nickname: 'Del Piero',     stars: 5, position: 'forward', active: true },
  { name: 'Andriy Shevchenko',    nickname: 'Sheva',         stars: 5, position: 'forward', active: true },
  { name: 'Gabriel Batistuta',    nickname: 'Batigol',       stars: 5, position: 'forward', active: true },
  { name: 'Samuel Eto\'o',        nickname: 'Eto\'o',        stars: 5, position: 'forward', active: true },
  { name: 'Didier Drogba',        nickname: 'Drogba',        stars: 5, position: 'forward', active: true },
  { name: 'Cristiano Ronaldo',    nickname: 'CR7',           stars: 5, position: 'forward', active: true },
  { name: 'Lionel Messi',         nickname: 'La Pulga',      stars: 5, position: 'forward', active: true },
  { name: 'Zlatan Ibrahimović',   nickname: 'Ibra',          stars: 5, position: 'forward', active: true },
  { name: 'Romário',              nickname: 'Baixinho',      stars: 5, position: 'forward', active: true },
  { name: 'Kylian Mbappé',        nickname: 'Mbappé',        stars: 5, position: 'forward', active: true },
  { name: 'Erling Haaland',       nickname: 'Haaland',       stars: 5, position: 'forward', active: true },
  { name: 'Luis Suárez',          nickname: 'Suárez',        stars: 5, position: 'forward', active: true },
  { name: 'Christian Vieri',      nickname: 'Vieri',         stars: 4, position: 'forward', active: true },
  { name: 'Wayne Rooney',         nickname: 'Rooney',        stars: 4, position: 'forward', active: true },
  { name: 'Fernando Torres',      nickname: 'El Niño',       stars: 4, position: 'forward', active: true },
  { name: 'David Trezeguet',      nickname: 'Trezeguet',     stars: 4, position: 'forward', active: true },
  { name: 'Filippo Inzaghi',      nickname: 'Pippo',         stars: 4, position: 'forward', active: true },
  { name: 'Hernán Crespo',        nickname: 'Crespo',        stars: 4, position: 'forward', active: true },
  { name: 'Patrick Kluivert',     nickname: 'Kluivert',      stars: 4, position: 'forward', active: true },
  { name: 'Antoine Griezmann',    nickname: 'Griezmann',     stars: 4, position: 'forward', active: true },
  { name: 'Édinson Cavani',       nickname: 'Cavani',        stars: 4, position: 'forward', active: true },
  { name: 'Harry Kane',           nickname: 'Kane',          stars: 4, position: 'forward', active: true },
  { name: 'Robson de Souza',      nickname: 'Robinho',       stars: 3, position: 'forward', active: true },
  { name: 'Obafemi Martins',      nickname: 'Oba Oba',       stars: 3, position: 'forward', active: true },
];

export function seedWithIds(): DrawPlayer[] {
  return SEED_PLAYERS.map((p, i) => ({ ...p, id: String(i) }));
}
