http:

  routers:
    api:
      rule: "Host(`api.rachao.app`)"
      entrypoints: [websecure]
      tls:
        certResolver: letsencrypt
      service: api

    frontend:
      rule: "Host(`rachao.app`)"
      entrypoints: [websecure]
      tls:
        certResolver: letsencrypt
        domains:
          - main: rachao.app
            sans: [www.rachao.app]
      service: frontend

    www:
      rule: "Host(`www.rachao.app`)"
      entrypoints: [websecure]
      tls:
        certResolver: letsencrypt
      middlewares: [www-redirect]
      service: frontend

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

  middlewares:
    www-redirect:
      redirectRegex:
        regex: "^https://www\\.rachao\\.app(.*)"
        replacement: "https://rachao.app${1}"
        permanent: true
